WIP Create step which is of number input
DFE-Digital/buy-for-your-school pull request #132
Opened 2021-01-27 17:07 UTC by LornaHarwood

We need a question which asks for a number rather that a short text
answer

## Changes in this PR

## Screenshots of UI changes

### Before

### After

## Next steps

2021-02-02 15:13 UTC, jacksonj04 requested changes

2021-02-02 16:19 UTC, LornaHarwood commented on spec/features/visitors/anyone_can_complete_a_journey_spec.rb
> +    context "when Contentful entry is of type numbers" do
👍 These have been added

2021-02-04 14:36 UTC, jacksonj04 requested changes
One very quick missing test, then I think this one's good to roll!

2021-02-04 14:36 UTC, jacksonj04 commented on app/presenters/number_answer_presenter.rb
> +class NumberAnswerPresenter < SimpleDelegator
For completeness we should add a test to confirm this behaves as intended - see `/spec/presenters` for some examples to base it on.

2021-02-04 15:18 UTC, LornaHarwood commented on app/presenters/number_answer_presenter.rb
> +class NumberAnswerPresenter < SimpleDelegator
💯 - I have added in a spec test for `NumberAnswerPresenter`

2021-02-04 15:56 UTC, jacksonj04 approved these changes
🚀

2021-02-04 17:12 UTC, merged