Refactor answer finding into a tested service
DFE-Digital/buy-for-your-school pull request #137
Opened 2021-01-28 17:38 UTC by tahb

## Changes in this PR

- straight refactor to move some heavy controller code into a class with unit test coverage

2021-02-02 09:43 UTC, jacksonj04 reviewed
Couple of lil' comments.

2021-02-02 09:43 UTC, jacksonj04 commented on app/services/find_all_journey_answers.rb
>        end
Could we slip an error case in here ([see similar](https://github.com/DFE-Digital/buy-for-your-school/pull/132/commits/04a440e43bac8f08a19da057a2518de30c387c90)) as we had to spend 10 minutes chasing this down whilst adding a number, and an explicit error would be handy

2021-02-02 09:43 UTC, jacksonj04 commented on app/services/find_all_journey_answers.rb
> +      next if step.answer.nil?
Could we do `next unless step.answer`? It seems more expressive, but it's a weakly held view.

2021-02-03 11:13 UTC, tahb commented on app/services/find_all_journey_answers.rb
>        end
Good idea! 👍

2021-02-03 11:14 UTC, jacksonj04 requested changes

2021-02-03 11:14 UTC, jacksonj04 commented on spec/services/find_all_journey_answers_spec.rb
> +    context "when a step does not have an answer" do
There's an extra case we should test here for "when the step has an answer of an unknown type", and it should either return the bare `Answer` or (I think more robustly) raise an exception.

2021-02-03 11:14 UTC, jacksonj04 commented on spec/services/find_all_journey_answers_spec.rb
> +      it_behaves_like "returns the answer in a hash", :short_text_answer, ShortTextAnswerPresenter, "Red"
`"returns the answer in a hash"` looks like a copy/paste oversight!

2021-02-03 11:22 UTC, tahb commented on spec/services/find_all_journey_answers_spec.rb
> +      it_behaves_like "returns the answer in a hash", :short_text_answer, ShortTextAnswerPresenter, "Red"
What do you think: "returns the answer against its step ID in a hash"?

2021-02-03 11:25 UTC, jacksonj04 commented on spec/services/find_all_journey_answers_spec.rb
> +      it_behaves_like "returns the answer in a hash", :short_text_answer, ShortTextAnswerPresenter, "Red"
I'd be tempted to use something like "returns the answer as a string in a hash", "returns the answer as HTML paragraphs in a hash", "returns the answer as a formatted date in a hash" etc since this is the only place we also test that the formatting of the answer is as expected.

2021-02-03 11:51 UTC, tahb commented on spec/services/find_all_journey_answers_spec.rb
> +      it_behaves_like "returns the answer in a hash", :short_text_answer, ShortTextAnswerPresenter, "Red"
"returns the answer as a string in a hash" sounds good to me.
 
We do have unit tests for the presenters so here we could settle for checked the right presenter is used and trust them to do their job from there? Otherwise, we could repeat our tests if we feel like we need more confidence.

2021-02-03 11:54 UTC, tahb commented on spec/services/find_all_journey_answers_spec.rb
> +      it_behaves_like "returns the answer in a hash", :short_text_answer, ShortTextAnswerPresenter, "Red"
Oh do you mean different descriptions for each test!? Ah, so the reason I'm being abstract is so I can use the same shared example to reduce repitition. Happy to remove them ?

2021-02-03 11:57 UTC, jacksonj04 approved these changes
Brain no do code. Ship it!

2021-02-03 11:57 UTC, jacksonj04 commented on spec/services/find_all_journey_answers_spec.rb
> +      it_behaves_like "returns the answer in a hash", :short_text_answer, ShortTextAnswerPresenter, "Red"
Ohhhhh, it's not a description is it, it's the name of the pattern!

Ignore me, not enough coffee has been applied to brain.

2021-02-03 11:59 UTC, tahb commented on spec/services/find_all_journey_answers_spec.rb
> +      it_behaves_like "returns the answer in a hash", :short_text_answer, ShortTextAnswerPresenter, "Red"
Roger! 🙌

2021-02-03 11:59 UTC, merged