Record interactions for additional changes
DFE-Digital/buy-for-your-school pull request #1414
Opened 2023-05-22 14:40 UTC by TimWilde

## Changes in this PR

Record interations for:
- Organisation changes
- Contact changes
- Support level changes

2023-05-23 09:42 UTC, ryantk requested changes
This will do the job but I would like to take the chance to move all case history logging into app/cores/case_history/x.rb

Take a look at the relationship between
`app/cores/case_management/assign_case_to_agent.rb`
and
`app/cores/case_history/handle_case_state_changes.rb`
taking note of `agent_assigned_to_case`.

We could either make the CaseXForm publish some events for the case_history core to listen to, or create a new object in the app/cores/case_management and delegate from the CaseXForms.

Please slack me if that doesn't make sense.

2023-05-23 11:02 UTC, TimWilde commented
Sounds good - I'll convert one of the three I've added then ask for another review to make sure I'm on the right track, before doing the rest :)

2023-05-24 14:56 UTC, ryantk approved these changes

2023-05-25 12:27 UTC, EdwinKruglov approved these changes

2023-05-26 10:01 UTC, merged