Replace contentful fixture with real API request
DFE-Digital/buy-for-your-school pull request #16
Opened 2020-10-29 16:59 UTC by tahb

* Use environment variables to make the client configurable in keeping with 12 factor apps
* Dotenv requires the new environment variables and gives helpful feedback to devs on app boot
* Hard code the entry to be the same as the fixture for now. We can replace this with a another environment variable next in it's own commit
* ContentfulHelpers added to add a stub method for the API, the service class itself includes a very similar setup but 'expects' rather than 'allows'.
* We know we'll need to handle other types of question/entry in the future so the filename can be passed in dynamically.

## Changes in this PR

## Screenshots of UI changes

### Before

### After

## Next steps

2020-11-02 15:51 UTC, jacksonj04 reviewed
A couple of tweaks around exactly how we interface with Contentful's mountain of different endpoints, environments and whatnot.

The process of retrieving content itself looks solid though!

2020-11-02 15:51 UTC, jacksonj04 commented on .env.example
> +# Contentful
We should probably also specify the Contentful API endpoint here, so we can use the [preview API](https://www.contentful.com/developers/docs/references/content-preview-api/).

Pre-emptively, we might want the one for the [environment](https://www.contentful.com/developers/docs/concepts/multiple-environments/) as well.

2020-11-02 15:51 UTC, jacksonj04 commented on app/services/get_contentful_question.rb
>  class GetContentfulQuestion
This might be better called `GetContentfulEntry` so the terminology lines up; also content types in Contentful include "question" and "decision", and this may well expand in future, but this method will retrieve them all.

2020-11-02 15:51 UTC, jacksonj04 commented on app/services/get_contentful_question.rb
> +      error_message = "The following Contentful entry identifier could not be found: #{entry_id}"
This should probably also include the environment, lest we try hunt down content in the wrong one. I don't think it needs the endpoint we're calling, as an entry of content will still exist in both live and preview.

2020-11-03 12:36 UTC, tahb commented on .env.example
> +# Contentful
I agree that we will likely need those configurable too. For me, that point is probably not as part of this pull request as this story isn't driving that feature out. That said these do appear to be small changes so I've added 2 new commits along the lines of a preoptimsation. Happy to keep them in unless they become contentious in which case it may be easier to leave them until later to get this work through 👍

2020-11-03 12:38 UTC, tahb commented on app/services/get_contentful_question.rb
>  class GetContentfulQuestion
Agree 🙌

2020-11-03 12:40 UTC, tahb commented on app/services/get_contentful_question.rb
>  class GetContentfulQuestion
Mm this service wasn't added in this pull request so I'm thinking it'll have to be a new commit.

2020-11-03 12:44 UTC, tahb commented on app/services/get_contentful_question.rb
> +      error_message = "The following Contentful entry identifier could not be found: #{entry_id}"
I agree with environment and think we should probably include the endpoint as well since it looks like it would change for the preview functionality https://www.contentful.com/developers/docs/references/content-preview-api/

2020-11-03 13:01 UTC, tahb commented on spec/services/get_contentful_entry_spec.rb
> +            contentful_entry_id: "123")
@jacksonj04 I made a further change in passing after your last look. I moved the entry ID out of the message and into the payload. This feels more natural and became obvious when I started adding more data in. 

I reckon if we put the entry_id in the message we'd end up with a unique rollbar event for each error too. My bad :)

2020-11-03 13:02 UTC, tahb commented
New commits: https://github.com/DFE-Digital/buy-for-your-school/pull/16/commits/bd44aa2ef8722878692853b864731f41261efeda, https://github.com/DFE-Digital/buy-for-your-school/pull/16/commits/9658568fbe5187617c549e3b0257ca27b209ff0b and https://github.com/DFE-Digital/buy-for-your-school/pull/16/commits/708630aa0f7875c6b7dca08c7832f85b95b17d9d. Back with you @jacksonj04

2020-11-03 13:09 UTC, jacksonj04 commented on spec/services/get_contentful_entry_spec.rb
> +            contentful_entry_id: "123")
Looks like a smart move to me!

2020-11-03 13:31 UTC, jacksonj04 approved these changes
Changes look good! ✅

2020-11-03 13:32 UTC, jacksonj04 requested changes
Ugh, just spotted that the review app isn't happy...

2020-11-03 13:35 UTC, jacksonj04 requested changes
The new Contentful API environment variables need adding to the `app.json` to allow review apps to run, but other than that this looks good!

2020-11-03 16:49 UTC, jacksonj04 approved these changes

2020-11-03 16:51 UTC, merged