WIP 1894 - fix(cms): add ability to remove framework
DFE-Digital/buy-for-your-school pull request #1722
Opened 2024-02-06 16:24 UTC by serenaabbott11

## Changes in this PR

## Screen-shots or screen-capture of UI changes

2024-02-07 13:38 UTC, ryantk requested changes
Looks good overall, just put a comment about avoiding "hard coding" the field names in the js controller which could make it brittle.

2024-02-07 13:38 UTC, ryantk commented on app/javascript/controllers/framework_edit_controller.js
> +      this.inputTarget.querySelector("[name='case_procurement_details_form[framework_name]']").addEventListener("change", this.toggle.bind(this));
Instead of using querySelector, make a new target and refer to it that way

2024-02-07 13:38 UTC, ryantk commented on app/javascript/controllers/framework_edit_controller.js
> +      document.getElementsByName("case_procurement_details_form[framework_name]")[0].value = "";
Is there a way we can avoid using the form name "case_procurement_details_form", perhaps a target?

2024-02-14 11:32 UTC, cocoaken approved these changes

2024-02-15 14:10 UTC, merged