(342) Users can answer using the extended checkbox pattern
DFE-Digital/buy-for-your-school pull request #174
Opened 2021-02-17 15:15 UTC by tahb

## Changes in this PR

Users can now be asked to provide further information for the choice they've made, if Contentful has specified that behaviour for the given answer

There should be no surprises here since we are following the precedent set by the extended-radio pattern. Fortunately the [DfE Form builder gem supports this "Other" mechanism](https://govuk-form-builder.netlify.app/form-elements/checkboxes/#generating-checkboxes-with-a-conditionally-revealed-text-field) in the same way. 

## Screenshots of UI changes

### Before
![Screenshot 2021-02-17 at 15 07 40](https://user-images.githubusercontent.com/912473/108224288-a8d88e00-7132-11eb-9863-9d20a1fee3dd.png)

### After
![Screenshot 2021-02-17 at 15 07 35](https://user-images.githubusercontent.com/912473/108224292-aa09bb00-7132-11eb-97bf-5cf8bc985ed4.png)

2021-02-18 11:19 UTC, jacksonj04 requested changes
A question to resolve around how this behaves with multiple extended options in a single checkbox set

2021-02-18 11:19 UTC, jacksonj04 commented on spec/features/visitors/anyone_can_complete_a_journey_spec.rb
> +          expect(find_field("answer-further-information-field").value)
I think it's worth having a test here to make sure that if we have _multiple_ extended checkbox fields then they all behave according to plan, ie each one can store its response differently.

2021-02-18 11:55 UTC, tahb commented on spec/features/visitors/anyone_can_complete_a_journey_spec.rb
> +          expect(find_field("answer-further-information-field").value)
Oh this is a major blunder! We can't store more than 1 piece of `further_information` in the same column, whilst it's a string at least. This is going to require more work.

2021-02-18 17:39 UTC, tahb commented
@jacksonj04 Ready for another look. Certainly not proud of this one but I can't see another way to do this without Javascript trickery.

2021-02-22 11:56 UTC, jacksonj04 approved these changes
Approve for _answering_, but we don't currently expose this in the answers variables. It might be worth pushing this into [this card](https://trello.com/c/Km749nb6/373-for-extended-radio-and-checkbox-questions-distinguish-between-the-provided-answer-which-was-chosen-and-the-extended-answer-which), which handles dealing with exposing answers in arrays and things.

2021-02-22 11:56 UTC, jacksonj04 commented on app/helpers/step_helper.rb
> +  def monkey_patch_form_object_with_further_information_field(
This is possibly one of my favourite method names to have ever reviewed, and is also entirely descriptive.

🔧 🐵

2021-02-22 12:07 UTC, merged