feat(crm): updating precision in support case columns
DFE-Digital/buy-for-your-school pull request #1921
Opened 2024-09-12 09:06 UTC by DevMagnataur

## Changes in this PR
Change the case value maximum number allowed

## Screen-shots or screen-capture of UI changes

2024-09-13 13:36 UTC, serenaabbott11 requested changes

2024-09-13 15:15 UTC, DevMagnataur commented on app/controllers/support/cases/additional_contacts_controller.rb
> -      @emails = @current_case.case_additional_contacts&.pluck(:email)
No

2024-09-13 15:16 UTC, DevMagnataur commented on app/controllers/support/establishments_controller.rb
> +          render json: EstablishmentSearch.omnisearch(params[:q]).where("establishment_type not in (?)", ["Federation", "Trust", "Single-academy Trust", "Multi-academy Trust", "Umbrella trust", "Loca
no

2024-09-13 15:16 UTC, DevMagnataur commented on app/forms/support/case_additional_contact_form_schema.rb
> +      optional(:first_name).value(:string)
no

2024-09-13 15:16 UTC, DevMagnataur commented on app/models/support/case_additional_contact.rb
> +    validates :email, presence: true
no

2024-09-16 08:40 UTC, serenaabbott11 approved these changes

2024-09-16 08:46 UTC, merged