PWNN-2090 Store FaF data in the CMS register as 'DfE approved' frameworks (from the FaF tool)
DFE-Digital/buy-for-your-school pull request #1972
Opened 2024-11-05 17:04 UTC by edwin-jebaraj

## Changes in this PR
Story 
PWNN-2090
PWNN-2092 
PWNN-2095
PWNN-2096

1. app/components/activity_log/history_item_component.rb - Added new label for faf tool import activity
2. app/controllers/frameworks/frameworks_controller.rb - Added sort by option to the Provider and Provider contact
3. app/models/frameworks/framework.rb - Added validation
4. app/models/frameworks/framework/sortable.rb - Removed unwanted sortable field 
5. app/models/frameworks/framework/sourceable.rb - Added new Source enum value for faf data import
6. app/models/frameworks/framework/status_changeable.rb - Updated status order and added new status value
7. app/services/support/sync_frameworks.rb - Updated framework import functionality 
8. app/views/frameworks/frameworks/_form.html.erb - Removed unwanted fields and added condition for FaF data non editable
9. app/views/frameworks/frameworks/_framework.html.erb - Removed unwanted fields on Framework listing
10. app/views/frameworks/frameworks/_index_filters.html.erb - Removed unwanted fields on framework filter
11. app/views/frameworks/frameworks/_status.html.erb - Added new status colour
12.  db/migrate/20241023161813_add_extra_fields_to_frameworks_frameworks.rb - Added extra fields to frameworks_frameworks table to import FaF data
13. db/migrate/20241023161813_add_extra_fields_to_frameworks_frameworks.rb - Added new unique index key
14. db/schema.rb - updated db migration

## Screen-shots or screen-capture of UI changes

2024-11-06 15:07 UTC, threedaymonk requested changes

2024-11-06 15:07 UTC, threedaymonk commented on app/views/frameworks/frameworks/_form.html.erb
> +        <p class="govuk-body-l"><%= @framework.status == 'dfe_approved'? 'DfE approved': @framework.status == 'cab_approved'? 'CAB approved': @framework.status.humanize %></p>
I don't think much of ternary operators at the best of times, and if you've got two of them nested on the same line it's a motivation to refactor it to something clearer.

This is a great opportunity to use localisation:

```ruby
I18n.t(@framework.status, scope: "support.framework_statuses",
  default: ->{ @framework.status.humanize })
```

combined with

```yaml
en:
  support:
    framework_statuses:
      cab_approved: CAB approved
      dfe_approved: DfE approved
```

2024-11-06 15:07 UTC, threedaymonk commented on app/views/frameworks/frameworks/_index_filters.html.erb
> +            <%= form.govuk_check_box :status, status.last, exclusive: false, label: { text: status.last == 'dfe_approved'? 'DfE approved': status.last == 'cab_approved'? 'CAB approved': status.first
as above, this needs refactoring with `I18n.t`

2024-11-07 17:31 UTC, edwin-jebaraj commented on app/services/support/sync_frameworks.rb
> +          Frameworks::Framework.find_by(id: cms_framework.id).update!(status: 5)
updated

2024-11-07 17:31 UTC, edwin-jebaraj commented on app/services/support/sync_frameworks.rb
> +      provider_detail = Frameworks::Provider.where("lower(short_name) = ?", provider_short_name.downcase).first
updated

2024-11-07 17:31 UTC, edwin-jebaraj commented on app/views/frameworks/frameworks/_form.html.erb
> +      <% end %>
updated

2024-11-07 17:31 UTC, edwin-jebaraj commented on app/views/frameworks/frameworks/_form.html.erb
> +            <p class="govuk-body-l"><%= @framework.provider_end_date.strftime("%d/%m/%Y")%></p>
updated

2024-11-07 17:32 UTC, edwin-jebaraj commented on app/views/frameworks/frameworks/_form.html.erb
> +        <p class="govuk-body-l"><%= @framework.status == 'dfe_approved'? 'DfE approved': @framework.status == 'cab_approved'? 'CAB approved': @framework.status.humanize %></p>
updated

2024-11-11 12:48 UTC, threedaymonk requested changes

2024-11-11 12:48 UTC, threedaymonk commented on app/services/support/sync_frameworks.rb
> +            status: get_expired_status(faf[:provider_end_date]),
Why don't we update `status` also?

If we did update status, we could avoid a lot of repetition here by using `find_or_initialize_by` followed by `update!`.

2024-11-11 12:48 UTC, threedaymonk commented on app/services/support/sync_frameworks.rb
> +      provider_detail = Frameworks::Provider.find_by("lower(short_name) = lower(?)", provider_short_name)
Perhaps a name like `existing_provider` might be clearer than `provider_detail`

2024-11-11 12:48 UTC, threedaymonk commented on app/services/support/sync_frameworks.rb
> +        provider_id
The `if` is redundant as `save!` raises an exception on failure.

2024-11-11 12:48 UTC, threedaymonk commented on app/services/support/sync_frameworks.rb
> +      @archived = Frameworks::Framework.statuses["archived"]
I don't think these instance variables help. I think it would be better to use `Frameworks::Framework.statuses[...]` directly, or if you wanted to be terser you could add

```ruby
delegate :statuses, to: Frameworks::Framework
```

and use `statuses[...]` directly.

2024-11-11 15:29 UTC, edwin-jebaraj commented on app/services/support/sync_frameworks.rb
> +            status: get_expired_status(faf[:provider_end_date]),
updated

2024-11-11 15:30 UTC, edwin-jebaraj commented on app/services/support/sync_frameworks.rb
> +      provider_detail = Frameworks::Provider.find_by("lower(short_name) = lower(?)", provider_short_name)
updated

2024-11-11 15:30 UTC, edwin-jebaraj commented on app/services/support/sync_frameworks.rb
> +      @archived = Frameworks::Framework.statuses["archived"]
updated

2024-11-11 17:20 UTC, threedaymonk requested changes

2024-11-11 17:20 UTC, threedaymonk commented on app/services/support/sync_frameworks.rb
> +          Frameworks::Provider.find_by!(id: provider.id).update!(name: provider_name) # to update provider name when title is diff
Isn't `Frameworks::Provider.find_by!(id: provider.id)` the same thing as `provider`?

2024-11-11 18:13 UTC, edwin-jebaraj commented on app/models/frameworks/framework.rb
> +      errors.add(:name, I18n.t("framework.validation.unique_name_and_provider"))
updated

2024-11-11 18:21 UTC, edwin-jebaraj commented on app/services/support/sync_frameworks.rb
> +          Frameworks::Provider.find_by!(id: provider.id).update!(name: provider_name) # to update provider name when title is diff
updated

2024-11-12 09:51 UTC, merged