PWNN-2097 Ability to select DfE approved or CAB approved framework
DFE-Digital/buy-for-your-school pull request #1998
Opened 2024-11-25 12:06 UTC by edwin-jebaraj

## Changes in this PR

**PWNN-2097 Ability to select DfE approved or CAB approved framework**

app/controllers/support/frameworks_controller.rb  - Added new condtion to filter approved framework

## Screen-shots or screen-capture of UI changes

2024-11-25 15:27 UTC, threedaymonk requested changes

2024-11-25 15:27 UTC, threedaymonk commented on app/controllers/support/frameworks_controller.rb
> +            .where(status: %w[dfe_approved cab_approved])
rather than putting this in the controller, can we have an "approved" named scope instead?

2024-11-25 18:21 UTC, edwin-jebaraj commented on app/controllers/support/frameworks_controller.rb
> +            .where(status: %w[dfe_approved cab_approved])
@threedaymonk  updated

2024-11-26 10:24 UTC, threedaymonk approved these changes
All good, please rebase and then it can be merged.

2024-11-26 10:38 UTC, merged