SC-107 Set due date
DFE-Digital/buy-for-your-school pull request #2004
Opened 2024-11-27 12:45 UTC by edwin-jebaraj

## Changes in this PR
1. app/controllers/support/cases/evaluation_due_dates_controller.rb - Added new controller to update evaluation due date
2. app/models/support/case.rb - Added evaluation due date validation
3. app/views/support/cases/evaluation_due_dates/edit.html.erb - Added new view file to update evaluation due date
4. config/locales/en.yml - Added new language variable
5. config/locales/validation/en.yml - Added nee validation language variable
6. config/routes.rb - Added new route for evaluation due date screen
7. db/migrate/20241126122758_add_evaluation_due_date_to_support_cases.rb - Added new migration file to add new field in support_cases table
8. spec/features/support/evaluation_due_dates/edit_evaluation_due_dates_spec.rb - Added new validation spec file for evaluaton due date

## Screen-shots or screen-capture of UI changes

2024-12-04 11:27 UTC, threedaymonk requested changes

2024-12-04 11:27 UTC, threedaymonk commented on app/controllers/support/cases/evaluation_due_dates_controller.rb
> +    before_action { @back_url = "/support/cases/#{params[:case_id]}#tasklist" }
This should use a URL helper with the [`anchor` parameter for the `#tasklist`](https://api.rubyonrails.org/classes/ActionView/Helpers/UrlHelper.html#:~:text=link_to%20can%20also,strings:)

```ruby
support_case_path(@current_case, anchor: "tasklist")
```

2024-12-04 11:27 UTC, threedaymonk commented on app/controllers/support/cases/evaluation_due_dates_controller.rb
> +        if @evaluation_due_date.save(context: :update_due_date_form)
You've already loaded the case and assigned it to `@current_case` in `set_current_case`.

2024-12-04 11:27 UTC, threedaymonk commented on app/controllers/support/cases/evaluation_due_dates_controller.rb
> +    end
You shouldn't have to do all this explicitly: `@current_case.update(params.require(:support_case).permit(:evaluation_due_date))` ought to work in Rails.

2024-12-05 11:22 UTC, edwin-jebaraj commented on app/controllers/support/cases/evaluation_due_dates_controller.rb
> +    before_action { @back_url = "/support/cases/#{params[:case_id]}#tasklist" }
Updated

2024-12-05 11:22 UTC, edwin-jebaraj commented on app/controllers/support/cases/evaluation_due_dates_controller.rb
> +        if @evaluation_due_date.save(context: :update_due_date_form)
updated

2024-12-09 11:28 UTC, threedaymonk requested changes

2024-12-09 11:28 UTC, threedaymonk commented on app/controllers/support/cases/evaluation_due_dates_controller.rb
> +        @current_case.update!(@case_evaluation_due_date_form.to_h)
It's still the same!

2024-12-09 11:57 UTC, threedaymonk approved these changes

2024-12-09 11:58 UTC, merged