SC-83 Invite evaluators to start evaluation tasks
DFE-Digital/buy-for-your-school pull request #2017
Opened 2024-12-12 18:10 UTC by edwin-jebaraj

## Changes in this PR
1. app/controllers/support/cases/email_evaluators_controller.rb - Added new controller
2. app/models/email/template_parser.rb - Added new parse variable
3. app/views/support/cases/email_evaluators/_document_list.html.erb - Added new view file to list uploaded documents
4. app/views/support/cases/email_evaluators/_email_list.html.erb - Added new view file to list evaluators
5. app/views/support/cases/email_evaluators/_form.html.erb - Added new form file
6. app/views/support/cases/email_evaluators/_form_template.html.erb - Added new default template file
7.  app/views/support/cases/email_evaluators/edit.html.erb - Added new view file
8. app/views/support/cases/show/_tasklist.html.erb - Updated email evaluator link in task list
9. config/locales/en.yml - added new language variable
10. config/routes.rb - Added new route for email_evaluators
11. db/migrate/20241211171744_add_sent_email_to_evaluators_to_case.rb - Added new migration file
12. spec/features/support/agent_can_email_to_evaluators_spec.rb - Added new spec file for testing

## Screen-shots or screen-capture of UI changes

2025-01-09 11:32 UTC, threedaymonk requested changes
Can we also test that the email is sent and that the link in the email goes somewhere useful, so that we have confidence in the whole process from end to end?

2025-01-09 11:32 UTC, threedaymonk commented on app/controllers/support/cases/email_evaluators_controller.rb
> +        "unique_case_specific_link" => "<a target='_blank' rel='noopener noreferrer' href='#{unique_link}'>unique case-specific link</a>",
This needs to be properly escaped. Ideally, we'd use [link_to].

It might be nice to extract the all the email sending into a separate object, maybe somewhere in `app/services`, because it feels a bit out of scope for the controller.

[link_to]: https://api.rubyonrails.org/classes/ActionView/Helpers/UrlHelper.html#method-i-link_to

2025-01-09 11:32 UTC, threedaymonk commented on app/models/email/template_parser.rb
> +      "evaluation_due_date" => "{{evaluation_due_date}}",
do you need the interpolation? Would this work?

```ruby
"organisation_name" => organisation_name,
# etc.
```

2025-01-09 11:32 UTC, threedaymonk commented on spec/features/support/agent_can_email_to_evaluators_spec.rb
> +    create(:support_email, :inbox, ticket: support_case, outlook_conversation_id: "OCID1", subject: "Email Vealuators", recipients: [{ "name" => "Test 1", "address" => "test1@email.com" }], unique_bo
Typo: Veaulators => Evaluators

2025-01-09 11:32 UTC, threedaymonk commented on spec/models/support/case_spec.rb
> +        "id,ref,category_id,request_text,support_level,status,state,created_at,updated_at,agent_id,first_name,last_name,email,phone_number,source,organisation_id,existing_contract_id,new_contract_id,
Is this generated CSV ingested anywhere? Do we really need every attribute in it? Can we delete it entirely?

2025-01-09 14:27 UTC, edwin-jebaraj commented on spec/features/support/agent_can_email_to_evaluators_spec.rb
> +    create(:support_email, :inbox, ticket: support_case, outlook_conversation_id: "OCID1", subject: "Email Vealuators", recipients: [{ "name" => "Test 1", "address" => "test1@email.com" }], unique_bo
Updated

2025-01-09 14:27 UTC, edwin-jebaraj commented on app/controllers/support/cases/email_evaluators_controller.rb
> +        "unique_case_specific_link" => "<a target='_blank' rel='noopener noreferrer' href='#{unique_link}'>unique case-specific link</a>",
Moved to new service file

2025-01-09 14:28 UTC, edwin-jebaraj commented on spec/models/support/case_spec.rb
> +        "id,ref,category_id,request_text,support_level,status,state,created_at,updated_at,agent_id,first_name,last_name,email,phone_number,source,organisation_id,existing_contract_id,new_contract_id,
removed

2025-01-09 14:31 UTC, edwin-jebaraj commented on app/models/email/template_parser.rb
> +      "evaluation_due_date" => "{{evaluation_due_date}}",
We need this for email template parsing

2025-01-13 11:41 UTC, threedaymonk commented on app/controllers/support/cases/email_evaluators_controller.rb
> +        "unique_case_specific_link" => "<a target='_blank' rel='noopener noreferrer' href='#{unique_link}'>unique case-specific link</a>",
I was thinking more that the whole of the template parsing should be extracted, so that the `parse_template` directives in the controller would be more like:

```ruby
@parse_template = SomeService.call(...)
```

2025-01-13 17:08 UTC, threedaymonk commented on app/services/support/email_evaluators_variable_parser.rb
> +        "a_or_an" => @current_case.sub_category.starts_with?("A", "E", "I", "O", "U") ? "an" : "a",
This is unfortunately much more complicated!

- A universal method
- An honour

It would be better to rewrite these emails so that they don't need an indefinite article, I think.

2025-01-16 16:34 UTC, threedaymonk commented on app/models/support/case.rb
> +    def sub_category_aeiou_format
I think I'd probably choose something that describes the outcome here - "sub category with indefinite article" - rather than the mechanism

2025-01-16 16:41 UTC, threedaymonk reviewed
I think this is OK, but I'm going to ask @serenaabbott11 to take a look as she's working more directly on this and might spot something I've missed.

2025-01-16 16:41 UTC, threedaymonk commented on app/views/support/cases/show/_tasklist.html.erb
> +        if (@current_case.evaluators.count > 0 && @current_case.evaluation_due_date && @current_case.has_uploaded_documents && @current_case.sent_email_to_evaluators)
instead of `count > 0`, `any?` would explain the intention better.

2025-01-16 16:41 UTC, threedaymonk commented on config/routes.rb
> +    get "verify/evaluator/link/:id", to: "tasks#edit", as: :verify_evaluators_unique_link
I was wondering whether this was going to end up unreasonably long with the already-long domain name in front, but I think it's OK as we're sending HTML emails.

2025-01-20 11:33 UTC, threedaymonk approved these changes

2025-01-20 11:35 UTC, merged