(490) Automatically remove stale Journey records
DFE-Digital/buy-for-your-school pull request #254
Opened 2021-03-30 14:04 UTC by tahb

Everytime a user starts a specification journey within the service it creates 100-200 database rows. Each row represents a copy of Contentful content, most commonly a question. We make this copy to ensure that the journey remains future proof if the content in Contentful changes (versioning) and if the Contentful service becomes unavailable.

We are finding that we are creating approximately 10,000 a week on staging on our Heroky hobby database which is the limit. Whilst our live database will have millions of rows the problem remains that many thousands of rows will become occupied over time and there is a big potential that many of them will serve no value. There is no option or need for users to delete old specifications we present in the dashboard so for now the service is going to slowly fill up and undoubtedly in 6months/1year's time the database limit will be hit, long after we have stopped developing.

The starting definition is the Journey isn't association with a _single_ answer *and* it hasn't been worked on in the last month. The time period is arbitrary so we can increase it to become more defensive if we are concerned we might accidentally delete journeys where users have invested their time and effort. I think with the stale check, 1 month is fine. If the user comes back they are likely going to create a new journey, if they look for an old one and don't find it, they will hopefully find the new call to action and not be frustrated since no effort is lost on their part.

## Changes in this PR

- add some state to the Journey to avoid ugly and expensive database queries to find all qualifying journeys
- add a service that will contain the definition of what stale means
- add a new job that runs nightly to remove all stale journeys (this could be run less frequently but I think running it often while the dev team is on hand is sensible for relatively little cost in having it run every night)

2021-03-31 13:41 UTC, lozette requested changes
A couple of comments!

2021-03-31 13:41 UTC, lozette commented on app/models/journey.rb
> +  def fresh!
We have a query about the name `fresh!` - this implies it's a query, when what this is doing is "freshening" the record. Maybe `freshen` or `touch` is better

2021-03-31 13:41 UTC, lozette commented on db/migrate/20210330105313_add_stale_state_to_journey.rb
> +class AddStaleStateToJourney < ActiveRecord::Migration[6.1]
We think the name `stale` doesn't accurately represent the state of the journey. Maybe something like `has_answers` or `started` is better. `stale` implies it hasn't been worked on for a while, but that's represented by the `last_worked_on` property from a later commit

2021-04-08 15:12 UTC, tahb commented
@lozette those changes are done and I added a new commit to make the date range configurable for staging.

2021-04-12 14:10 UTC, lozette approved these changes

2021-04-12 15:59 UTC, tahb commented
I suspect that this job won't run on staging until this error is properly understood https://github.com/DFE-Digital/buy-for-your-school/pull/279.

Holding pattern ✈️

2021-04-14 16:33 UTC, merged