Add email address within header banner for feedback purposes
DFE-Digital/buy-for-your-school pull request #288
Opened 2021-04-15 13:59 UTC by LornaHarwood

## Changes in this PR

## Screenshots of UI changes

### Before

### After

## Next steps

2021-04-19 10:47 UTC, jacksonj04 requested changes

2021-04-19 10:47 UTC, jacksonj04 commented on config/locales/en.yml
> +          This is a new service – your <a href="mailto:schools.digital@education.gov.uk" class="govuk-link">feedback</a> will help us to improve it.
I'd be tempted to make this email address a global variable somewhere, since we use it in a few places and it might change in future.

2021-04-19 11:31 UTC, jacksonj04 commented
Other drive-by thought: this should probably have a changelog entry!

2021-04-19 13:57 UTC, LornaHarwood commented
> Other drive-by thought: this should probably have a changelog entry!

I had forgotton to do a final git push with the changelog entry 🤦 -  it is there now

2021-04-19 13:59 UTC, LornaHarwood commented on config/locales/en.yml
> +          This is a new service – your <a href="mailto:schools.digital@education.gov.uk" class="govuk-link">feedback</a> will help us to improve it.
Good point - do you have an idea of where it could sit?

2021-04-21 15:34 UTC, jacksonj04 approved these changes
One comment to make sure you include the ENV variables in the Terraform files (and then set them in the environments when this is merged), otherwise 👍🏼

2021-04-21 15:34 UTC, jacksonj04 commented on .env.example
> +SUPPORT_EMAIL=email@example.gov.uk
This will also need adding to the files in `/terraform/workspace-variables` so it's available for GPaaS deployments

2021-04-22 08:11 UTC, merged