Document how to change environment variables
DFE-Digital/buy-for-your-school pull request #309
Opened 2021-04-22 10:23 UTC by tahb

- Document how to view, change and apply environment variables on the live GPaaS environments.
- We make a minor addition to local environment management to include reference to our Dotenv initialiser for use with critical variables whose absense would prevent the app starting.

2021-04-26 09:35 UTC, lozette approved these changes
Approved but one small change required

2021-04-26 09:35 UTC, lozette commented on doc/managing-environment-variables.md
> +If the environment is critical whereby it is required to start the application, please add it to [the Dotenv initialiser](../config/initializers/_dotenv.rb).
Missing word `If the environment VARIABLE...`

2021-04-26 15:27 UTC, jacksonj04 requested changes
One tiny tweak to make sure the docs are correct!

2021-04-26 15:27 UTC, jacksonj04 commented on doc/managing-environment-variables.md
> +APP_ENV_PREVIVEW_
```suggestion
APP_ENV_PREVIEW_
```

2021-04-26 17:08 UTC, tahb commented
2 extra commits that I fixed as CI was failing intermittently (after turning tests back on in CI presumably). Piggy backing on this PR.

2021-04-29 14:39 UTC, jacksonj04 approved these changes

2021-04-29 15:10 UTC, merged