#189: Create Category Model
DFE-Digital/buy-for-your-school pull request #421
Opened 2021-07-01 15:33 UTC by EdwinKruglov

## Changes in this PR

- Add new entity `Category`
- Update entity `Journey` with `state` column and association to `Category`
- Add Rake task `migrate_to_category` to migrate existing `Journeys` to the new model
- Update `Journey` services, view, and controller to cope with the new model

2021-07-02 06:54 UTC, AndrewCowle commented
I'm reviewing this morning - give you a shout apres standup

2021-07-02 07:07 UTC, AndrewCowle requested changes

2021-07-02 07:07 UTC, AndrewCowle commented on app/models/journey.rb
> +  enum state: { started: 0, abandoned: 1, completed: 2, archived: 3, stale: 4 }
Might be worth using state machine here so we can extend upon it later

https://github.com/aasm/aasm

2021-07-02 07:07 UTC, AndrewCowle commented on db/migrate/20210630125559_create_categories.rb
> +      t.timestamps
will also need a `t.integer :journeys_count` for the counter cache to work

2021-07-02 13:46 UTC, EdwinKruglov commented on spec/services/create_journey_spec.rb
> +      xit "raises an error" do
@AndrewCowle,  I've x'ed this one out for now. This test tries to assert that an exception is raised when a `Journey` is saved with `category = nil`. Now that `Category` is its own entity, `Journey.category` has been removed, so this test no longer applies. Contentful's `category.title` used to be assigned `Journey.category` and fixture `category-with-no-title` provides a category with no title. But now, since we're storing `Categories` in the DB, we're associating them to `Journeys` instead. This kind of test might be more appropriate for when we update our Contentful services to fetch all the categories and populate our DB with them.

2021-07-05 08:35 UTC, peterdavidhamilton commented on app/models/journey.rb
> +  include AASM
I don't think we should introduce a dependency with a new DSL this early on.

2021-07-05 08:39 UTC, peterdavidhamilton commented on db/migrate/20210630125559_create_categories.rb
> +      t.string :name, null: false
I should've used `title` here so that it follows the same pattern as the other models. Can we swap it out please?

2021-07-05 08:46 UTC, peterdavidhamilton commented on app/services/create_journey.rb
> +      liquid_template: contentful_category.combined_specification_template,
Shouldn't this be in the Category @AndrewCowle and do we need the `contentful_id` in the Journey now we are associated with a category?

2021-07-06 07:23 UTC, peterdavidhamilton commented on app/controllers/journeys_controller.rb
> +  def get_category(category_id = nil)
If we make the exisiting category id the default param we can simplify this method:
```ruby
  def get_category(category_id = ENV["CONTENTFUL_DEFAULT_CATEGORY_ENTRY_ID"])
    Category.find_or_create_by!(contentful_id: category_id) do |category|
      contentful_category = GetCategory.new(category_entry_id: category.contentful_id).call
      category.title = contentful_category.title
      category.liquid_template = contentful_category.combined_specification_template
    end
  end
```

2021-07-06 07:29 UTC, peterdavidhamilton commented on app/models/journey.rb
> +  enum state: { started: 0, abandoned: 1, completed: 2, archived: 3, stale: 4 }
I know we have _state_ on the `Journey`, now I have thought about it, these states are wrong. We should have a quick chat to identify the correct _states_.

2021-07-06 15:58 UTC, peterdavidhamilton commented on app/models/journey.rb
> +  enum state: { deleted: 0, archived: 1, stale: 2 }
Can we change this so the default isn't `deleted` and escalates in severity using the present tense?
It would be good to add comments to clarify the reasoning.

```ruby
{  default: 0, stale: 1, archive: 2, delete: 3 }
```

- default: I'm sure a better word exists...
- stale: automatic flag the journey as being untouched for a while and something we could maybe purge
- archive: user-defined flag so it could be hidden from their dashboard
- delete: user-defined flag so it can be safely deleted (the _soft delete_ functionality)

2021-07-06 16:00 UTC, peterdavidhamilton commented on app/models/journey.rb
>    belongs_to :user
Please could we move the `belongs_to` above the `has_many` with a line in between? 
![bitmoji](https://sdk.bitmoji.com/render/panel/339bcdff-a351-499f-9fa3-f6516daf08ae-0aa0f111-c94b-4c89-a0cf-d486a7b9da7b-v1.png?transparent=1&palette=1&width=246)

2021-07-07 06:43 UTC, AndrewCowle approved these changes

2021-07-07 07:59 UTC, peterdavidhamilton commented
When you finally merge it @EdwinKruglov be sure to have a nice tidy commit message that lists all the changes.

2021-07-07 08:42 UTC, merged