Replace fixtures with factory
DFE-Digital/buy-for-your-school pull request #593
Opened 2021-10-26 14:52 UTC by PiperS52

## Changes in this PR

- refactoring relevant test files across code base, replacing fixtures with use of factories

2021-11-10 17:23 UTC, peterdavidhamilton commented on spec/features/self-serve/journeys/task_list/view_hidden_spec.rb
> +          [{ "value" => "School expert",
Was expecting to see `options` and other `json` fields pulled out in to `let` for the goal of readibility, formatting, but likely also handy for testing other contexts

2021-11-10 17:38 UTC, peterdavidhamilton requested changes
There are more files in the test suite that didn't have `NOTES` identifying them but they are also on the cards. If you can identify them these are going to be good tasks to fall back on whilst waiting for a code review.

2021-11-10 17:38 UTC, peterdavidhamilton commented on spec/features/self-serve/journeys/task_list/view_steps_spec.rb
> +        click_on "Long text task" # > checkboxes_task.json
The comments that help guide someone to the old `json` fixture are no longer relevant but at worse could be missleading if left in.

2021-11-10 17:38 UTC, peterdavidhamilton commented on spec/features/self-serve/metrics/log_view_task_spec.rb
> +        expect(last_logged_event.contentful_section_id).to eq "contentful-section-entry"
I think what would be wisest when refactoring specs is to never change the tests until after. So here you're not only replacing fixtures with factories but also effecting the assertions. Rather, build a `section` whose `id` exactly matches that coming from the old fixture. It might be fine, but changing both at the same time could be problematic.

2021-11-10 17:38 UTC, peterdavidhamilton commented on spec/features/self-serve/steps/presenter_spec.rb
> +    specify do
What does the output look like in the `documentation` format? Can we add a description to these blocks to make it any better in your opinion?

2021-11-10 17:39 UTC, peterdavidhamilton commented on app/models/journey.rb
> +    next_in_order = sections.includes([:tasks]).detect do |section|
So this was where you silenced that Bullet n+1 error?

2021-11-10 17:42 UTC, peterdavidhamilton commented on spec/features/self-serve/journeys/task_list/view_answered_spec.rb
> +  let(:section_one) { create(:section, title: "Catering", journey: journey, contentful_id: "contentful-section-entry") }
`section_one` and below `section_two` don't have their `order` set unless I'm mistaken. Does this mean that sometimes they are reversed?

2021-11-11 14:47 UTC, PiperS52 commented on app/models/journey.rb
> +    next_in_order = sections.includes([:tasks]).detect do |section|
Yeah

2021-11-11 16:49 UTC, PiperS52 commented on spec/features/self-serve/journeys/task_list/view_steps_spec.rb
> +      click_continue # > error clicking 'Continue'
bug flagging - I've removed

2021-11-12 11:01 UTC, PiperS52 commented on spec/features/self-serve/journeys/task_list/view_answered_spec.rb
> +  let(:section_one) { create(:section, title: "Catering", journey: journey, contentful_id: "contentful-section-entry") }
Order doesn't seem to be necessary as section_two is only used on it's own for a single context

2021-11-12 14:34 UTC, PiperS52 commented on spec/features/self-serve/steps/presenter_spec.rb
> +    specify do
Description added to make tests clearer

2021-11-19 12:11 UTC, EdwinKruglov approved these changes

2021-11-19 12:46 UTC, d-a-v-e approved these changes
much clearer with the factories, nice work.

2021-11-19 17:01 UTC, peterdavidhamilton commented on spec/features/self-serve/journeys/task_list/view_steps_spec.rb
> +        click_on "Long text task" # > checkboxes_task.json
Can we get rid of the mention of `checkboxes_task.json` please and anything else that is now unrelated

2021-11-19 17:03 UTC, peterdavidhamilton approved these changes

2021-11-19 17:05 UTC, peterdavidhamilton commented
Time well spent 

![bitmoji](https://sdk.bitmoji.com/render/panel/c01f75cb-46fb-48c6-b217-e765d364b6c9-f42aca3a-54e1-4a1a-85c9-35b7f3d43af6-v1.png?transparent=1&palette=1&width=246)

2021-11-22 09:44 UTC, merged