DSI uses ENV
DFE-Digital/buy-for-your-school pull request #614
Opened 2021-10-29 15:48 UTC by d-a-v-e

## Changes in this PR

- consolidate DSI linking building logic into a dedicated class
- return a URI that defaults to the production environment
- add `DSI_ENV` to control the environment and link prefix
- remove `DFE_SIGN_IN_ISSUER` and `DFE_SIGN_IN_API_ENDPOINT`

## TODO

- delete old environment variables from the GH settings

2021-11-01 15:13 UTC, peterdavidhamilton commented
![](https://github.trello.services/images/mini-trello-icon.png) [DSI env for use in link logic](https://trello.com/c/KTT97ahO/780-dsi-env-for-use-in-link-logic)

2021-11-01 16:05 UTC, peterdavidhamilton commented on app/helpers/application_helper.rb
>    def dsi_url(args = {})
Can we slurp and splat on this?

2021-11-01 16:06 UTC, peterdavidhamilton commented on lib/dsi/client.rb
>      # @return [URI::HTTPS]
Can you document the `@param`

2021-11-01 16:08 UTC, peterdavidhamilton commented on spec/lib/self-serve/dsi/uri_spec.rb
> +  # TODO: replace meta-programmed testing to explicit context blocks
This is even more complex than before.

2021-11-01 16:09 UTC, peterdavidhamilton commented on spec/lib/self-serve/dsi/uri_spec.rb
> +        @original_dsi_env = ENV["DSI_ENV"]
Does this work? `ClimateControl.modify(DSI_ENV: nil) { example.run }`

2021-11-01 16:10 UTC, peterdavidhamilton commented on spec/lib/self-serve/dsi/uri_spec.rb
> +        @original_dsi_env = ENV["DSI_ENV"]
Previous example used 
```ruby
around do |example|
  ClimateControl.modify(DSI_ENV: "test") { example.run }
end
```

2021-11-01 16:14 UTC, peterdavidhamilton commented on spec/lib/self-serve/dsi/uri_spec.rb
> +  # TODO: replace meta-programmed testing to explicit context blocks
I'll do a version at a later date to see what you think

2021-11-01 16:23 UTC, peterdavidhamilton commented on lib/dsi/client.rb
> +# require "dsi/url"
`require "dsi/uri"`

2021-11-01 16:24 UTC, peterdavidhamilton commented on lib/dsi/uri.rb
> +    # @!attribute [r] env
The `[r]` is the syntax for read-only so can be removed

2021-11-01 16:26 UTC, peterdavidhamilton requested changes
Can you address the comments please but leave the spec and I'll do a comparison

2021-11-03 08:49 UTC, peterdavidhamilton commented on app/helpers/application_helper.rb
> +    ::Dsi::Uri.new(args).call.to_s
Can we splat too?

2021-11-03 10:09 UTC, d-a-v-e commented on app/helpers/application_helper.rb
> +    ::Dsi::Uri.new(args).call.to_s
does it make sense to splat it if it's already been splatted (this is a very normal sentence to write)

2021-11-03 10:31 UTC, peterdavidhamilton approved these changes

2021-11-03 10:35 UTC, kennyevil approved these changes

2021-11-03 10:35 UTC, merged