[feature/766] - Add Qualtrics survey link
DFE-Digital/buy-for-your-school pull request #637
Opened 2021-11-03 16:22 UTC by d-a-v-e

## Changes in this PR

Button linking to Qualtrics added to view specifications page

## Screenshots of UI changes

### Before

<img width="753" alt="Screenshot 2021-11-03 at 16 20 26" src="https://user-images.githubusercontent.com/6339025/140100730-75536948-cd79-493a-b78a-6e50ed601d1e.png">

### After

<img width="765" alt="Screenshot 2021-11-03 at 16 19 52" src="https://user-images.githubusercontent.com/6339025/140100755-c6b2eb5f-15d0-4100-bc63-9c838502b12d.png">

2021-11-03 16:23 UTC, d-a-v-e commented
@peterdavidhamilton little unsure where to add this in the changelog, can you sanity check where I've put it?

2021-11-03 16:23 UTC, d-a-v-e commented
![](https://github.trello.services/images/mini-trello-icon.png) [Qualtrics survey link](https://trello.com/c/vugnvaW0/766-qualtrics-survey-link)

2021-11-03 16:48 UTC, peterdavidhamilton commented on .env.example
> +QUALTRICS_SURVEY_URL=https://dferesearch.fra1.qualtrics.com/jfe/form/SV_cH0KmiM6qDX3Bye
Best not include the actual env value here

2021-11-03 16:48 UTC, peterdavidhamilton commented on .env.test
> +QUALTRICS_SURVEY_URL=https://dferesearch.fra1.qualtrics.com/jfe/form/SV_cH0KmiM6qDX3Bye
Or here

2021-11-03 16:49 UTC, peterdavidhamilton commented on config/locales/en.yml
> +        title: Giving us feedback
Can we use keys of `heading`, `body`, `button` please

2021-11-03 16:52 UTC, peterdavidhamilton commented on spec/features/self-serve/journeys/download_spec.rb
> +      # journey.specification.feedback.text
Would using a `within` block around some assertions improve this?

2021-11-03 16:56 UTC, peterdavidhamilton commented on app/views/specifications/show.html.erb
> +  <%= button_to t("journey.specification.feedback.button_text"), ENV.fetch('QUALTRICS_SURVEY_URL'), class: "govuk-button govuk-button--secondary", "data-module" => "govuk-button" %>
`link_to` should get styled the same, we don't have a test that asserts the value of `QUALTRICS_SURVEY_URL` is being used in the link though. I think that's important.

2021-11-03 16:57 UTC, peterdavidhamilton commented on app/views/specifications/show.html.erb
> +    <%= t("journey.specification.feedback.title") %>
Can we stick with `I8n.t` for consistency for now

2021-11-03 16:59 UTC, peterdavidhamilton requested changes
Some pedantry but the feature test coverage of the env is essential

2021-11-03 19:27 UTC, d-a-v-e commented on spec/features/self-serve/journeys/download_spec.rb
> +      expect(find("a.govuk-button:contains('Download (.docx)')")[:role]).to eq "button"
@peterdavidhamilton 

Finding the project expectation of these feature specs a tad confusing. I've ended up with this as a result...which looks convoluted to me.

I'd have just relied on the `click_on` further down to confirm this is on the page, but thought If I removed this it would end up not getting a pass in review again.

If I leave it as it is, It clashes with the other `a.govuk-button` .. I suppose I could add another class to distinguish between this lin and the `Give feedback (opens in a new tab)` link but that feels wrong too.

2021-11-04 08:23 UTC, peterdavidhamilton commented
@d-a-v-e `CHANGELOG` is fine, it's just because we have been forced to go without a tagged release for a while and have essentially two logs to split now. There is a ticket to tidy and divide the log before a proper release version.

2021-11-04 08:34 UTC, peterdavidhamilton commented on spec/features/self-serve/journeys/download_spec.rb
> +      expect(find("a.govuk-button:contains('Download (.docx)')")[:role]).to eq "button"
You will not find consistency on all the specs yet, which is something we are working towards, it is evident there is a mix of developer approaches in play. My opinion is that the specs should not depend on any code internals and would therefore check against raw strings for example. When asserting page content, start with `expect(page).to` but as complexity increases the goal would be to articulate the key takeaways that the page is trying to achieve. So if there is a particular tag or class being used, consider if there is improved clarity by looking that up. There is a balance and I guess what I'm saying is, be as specific as you need to add value to the test, which is going to depend on the content and structure.

2021-11-04 08:38 UTC, peterdavidhamilton commented on spec/features/self-serve/journeys/download_spec.rb
> +        expect(page).to have_link("Give feedback (opens in a new tab)", href: "https://dferesearch.fra1.qualtrics.com")
For example, asserting that the class `govuk-button--secondary` exists on this link would tell me it is different to the other link, and that it is not green. I'd like to see headings get found because then the spec reads like the page and you can tell the structure, I can infer that from the locales comment but only because of the `heading` key.

2021-11-04 08:42 UTC, peterdavidhamilton commented on spec/features/self-serve/journeys/download_spec.rb
> +      expect(find("a.govuk-button:contains('Download (.docx)')")[:role]).to eq "button"
The more appropriate finder for this tag is probably `have_link`

2021-11-04 08:43 UTC, peterdavidhamilton commented on CHANGELOG.md
> +- provide qualtrics feedback link
Upon reflection, mentioning `QUALTRICS_SURVEY_URL` would be useful.

2021-11-04 12:47 UTC, peterdavidhamilton submitted a review, later dismissed
Could you add the `h2`, button class, and remove the byebug history please, then this is good.

2021-11-05 09:57 UTC, peterdavidhamilton approved these changes

2021-11-05 11:35 UTC, EdwinKruglov approved these changes

2021-11-05 11:46 UTC, PiperS52 approved these changes

2021-11-05 15:28 UTC, merged