Correct yard syntax for dry-initialiser classes
DFE-Digital/buy-for-your-school pull request #654
Opened 2021-11-10 14:11 UTC by EdwinKruglov

## Changes in this PR

- update yard documentation for dry-initializer `options` and `params`

2021-11-10 14:25 UTC, EdwinKruglov commented
![](https://github.trello.services/images/mini-trello-icon.png) [Correct yard syntax for dry-initialiser classes](https://trello.com/c/2hnEtIm9/781-correct-yard-syntax-for-dry-initialiser-classes)

2021-11-11 10:26 UTC, ryantk approved these changes

2021-11-11 10:50 UTC, peterdavidhamilton requested changes
The indentation is inconsistent but I don't know if that matters. I'd like to see things indented under `@attribute` please, and if `default` is set, it'd be good to see that in the doc

2021-11-12 09:44 UTC, EdwinKruglov commented
> The indentation is inconsistent but I don't know if that matters. I'd like to see things indented under `@attribute` please, and if `default` is set, it'd be good to see that in the doc

@peterdavidhamilton I've fixed the indentation and added a note about default values where necessary. I was hoping YARD would have a `@default` tag or similar, but it doesn't, so I just mentioned the default values on the `@return` tag.

2021-11-12 10:44 UTC, PiperS52 approved these changes

2021-11-15 16:41 UTC, peterdavidhamilton approved these changes

2021-11-16 09:06 UTC, merged