Page services
DFE-Digital/buy-for-your-school pull request #664
Opened 2021-11-18 09:13 UTC by EdwinKruglov

## Changes in this PR

- add `get` and `build` services for `Pages`

2021-11-18 09:42 UTC, EdwinKruglov commented
![](https://github.trello.services/images/mini-trello-icon.png) [Pages service object](https://trello.com/c/zTn8EZPz/31-pages-service-object)

2021-11-18 14:19 UTC, ryantk commented on app/services/content/page/get.rb
> +    GetEntry.new(entry_id: page_entry_id, client: client).call
There is very little difference between this class and GetEntry I would argue they could be collapsed into one.

2021-11-18 16:10 UTC, peterdavidhamilton commented on app/services/content/page/get.rb
> +    GetEntry.new(entry_id: page_entry_id, client: client).call
I'm imagining that this is because we are setting ourselves up to bypass the cache on the Page model, and caching happens in GetEntry, so we need something very similar so we can isolate this without impacting other things. @EdwinKruglov?

2021-11-18 16:19 UTC, peterdavidhamilton commented on spec/services/self-serve/content/page/get_spec.rb
> +  # rubocop:disable RSpec/AnyInstance
Depending on the circumstances we should leverage the rubocop todo file, sometimes that will guide us to changing the rules.

2021-11-18 16:29 UTC, ryantk commented on app/services/content/page/get.rb
> +    GetEntry.new(entry_id: page_entry_id, client: client).call
I feel there may be better ways to isolate in that case, but it also sounds like YAGNI.

2021-11-18 17:12 UTC, d-a-v-e commented on app/services/content/page/build.rb
> +    Page.find_by(contentful_id: contentful_page.id)
does returning `page` not work here?

2021-11-18 17:20 UTC, d-a-v-e requested changes

2021-11-18 17:20 UTC, d-a-v-e commented on app/services/content/page/build.rb
> +    Page.find_by(contentful_id: contentful_page.id)
does returning `page` not work here?

2021-11-18 17:20 UTC, d-a-v-e commented on app/services/content/page/build.rb
> +# Persits Page entries from Contentful
lil typo

2021-11-18 17:20 UTC, d-a-v-e commented on app/services/content/page/build.rb
> +  option :contentful_page
suggestion:

```ruby
# @!attribute env
    #   @return [Contentful::Entry] Contentful "Page" entity
    #   @api private
option :contenful_page, optional: false, reader: private
```

2021-11-18 17:20 UTC, d-a-v-e commented on app/services/content/page/build.rb
> +      returning: %w[title contentful_id slug body sidebar],
Maybe just return title, contentful_id, slug

2021-11-18 17:20 UTC, d-a-v-e commented on config/static/terms_and_conditions.md
> +- any loss or damage caused by civil wrongs ('tort', including negligence, duty of care or public law duty), breach of contract or otherwise
you can remove this (it's already in develop)

2021-11-19 08:30 UTC, EdwinKruglov commented on app/services/content/page/build.rb
> +    Page.find_by(contentful_id: contentful_page.id)
[`upsert`](https://edgeapi.rubyonrails.org/classes/ActiveRecord/Persistence/ClassMethods.html#method-i-upsert_all) does not return a model object, but an `ActiveRecord::Result`, so I need to make another query to get the actual `Page`.

2021-11-19 12:37 UTC, d-a-v-e approved these changes

2021-11-19 12:59 UTC, peterdavidhamilton commented on app/services/content/page/build.rb
> +  option :contentful_page, optional: false, reader: :private
@d-a-v-e might have mentioned consistent indentation already. I think that type checking the input is more powerful that `optional: false` because that is expected anyway.

2021-11-19 13:02 UTC, peterdavidhamilton commented on app/services/content/page/get.rb
> +    page = client.by_id(page_entry_id)
Not having looked into how this connects, but just a reminder that returning a `:useful_symbol` is sometimes a better return value than nil. You'll have seen this in the org checking code.

2021-11-19 13:18 UTC, peterdavidhamilton commented on app/services/content/page/get.rb
> +    GetEntry.new(entry_id: page_entry_id, client: client).call
@ryantk what is needed is a quick reliable response from Contentful with sensible webhook endpoints, and caching that helps not hinders. I know @EdwinKruglov is going to reflect on how code can be reviewed more easily by setting out his stall. Could you signpost him to "the better ways" or grab a quick chat together maybe.

2021-11-19 14:12 UTC, EdwinKruglov commented on app/services/content/page/build.rb
> +  option :contentful_page, optional: false, reader: :private
I wanted to add type checking to this field, but that makes it difficult to test it. It's not a fan of doubles.

2021-11-19 15:52 UTC, d-a-v-e approved these changes

2021-11-19 16:21 UTC, ryantk approved these changes

2021-11-19 16:46 UTC, peterdavidhamilton commented on app/services/content/page/build.rb
> +  option :contentful_page, optional: false, reader: :private
I'd suggest removing the `optional` key because it doesn't do anything. 

Consider not using a double? Depending on the test you could instantiate with `Contentful::Entry.new({}, {})` but pass in the `Hash` of attributes you need.

I mean `Types::Nominal::Any` is a thing though it doesn't add much value. The `Hash` is parsed `JSON` from the client and one of the things we can consider is if pure `JSON` is better for us at some point.

2021-11-19 16:46 UTC, peterdavidhamilton approved these changes

2021-11-19 17:22 UTC, merged