dynamic routes
DFE-Digital/buy-for-your-school pull request #669
Opened 2021-11-19 17:20 UTC by d-a-v-e

## Changes in this PR

## Screenshots of UI changes

### Before

### After

## Next steps

2021-11-19 17:20 UTC, d-a-v-e commented
![](https://github.trello.services/images/mini-trello-icon.png) [Dynamic routes](https://trello.com/c/HQLTiFOh/34-dynamic-routes)

2021-11-23 13:37 UTC, peterdavidhamilton commented on config/routes.rb
> +  # Dyamic Pages (Page refreshes routes on create commits)
typo

2021-11-23 14:51 UTC, d-a-v-e commented
@peterdavidhamilton @EdwinKruglov @PiperS52 

I've removed the dynamically generated routes block and replaced with a generic routing to `Pages`

I assume this will fix the issue we were seeing in docker!

2021-11-23 16:05 UTC, EdwinKruglov approved these changes

2021-11-24 10:50 UTC, peterdavidhamilton requested changes
@d-a-v-e we should add an ADR to document the move away from `high_voltage` (which doesn't have an ADR) to using Contentful to power page content. Try using the cli tool

2021-11-24 12:22 UTC, peterdavidhamilton approved these changes

2021-11-24 12:32 UTC, merged