Add support case activity logging
DFE-Digital/buy-for-your-school pull request #672
Opened 2021-11-23 09:05 UTC by kennyevil

## Changes in this PR

Adds ActivityLogItem for support cases.

2021-11-23 11:34 UTC, peterdavidhamilton requested changes
Does it make sense to also use `Support::RecordAction` and follow the same naming convention in the namespace?

2021-11-23 11:34 UTC, peterdavidhamilton commented on app/services/support/record_support_case_action.rb
> +    ACTION_TYPES = %w[
I think we should keep the imperative mood of the actions so `open_case` rather than `opening_case`.

2021-11-23 11:34 UTC, peterdavidhamilton commented on app/services/support/record_support_case_action.rb
> +
Might need to tidy the YARD syntax a little, remove line gap and change UUID to String. Could we also adopt `dry-intitializer` here instead so that we can benefit from type checking the action when we initialise.

2021-11-23 13:15 UTC, peterdavidhamilton commented on app/services/support/record_action.rb
> +    option :action, Types::String
We could still report to rollbar by rescuing in the controller methods though. What's your opinion?

2021-11-23 13:23 UTC, kennyevil commented on app/services/support/record_action.rb
> +    option :action, Types::String
There's very few places that this action is called and certainly none of them can be affected by a malicious user. It feels like a custom error isn't really necessary as it probably isn't ever going to be used. If there is an issue with the code, having the stack trace from a standard rollbar error will probably be enough to determine the cause. I'll take out the custom error type.

2021-11-24 07:49 UTC, peterdavidhamilton commented on spec/services/support/record_action_spec.rb
>            ).call
This will error even before we get to call it so it would be good to have the `call` removed.

2021-11-24 07:52 UTC, peterdavidhamilton requested changes
```ruby
context "when the action does has additional parameters specified" do
end
```

The spec could be improved with a tweak to the text

2021-11-24 07:53 UTC, peterdavidhamilton commented on app/services/support/record_action.rb
> +    # TODO: add RecordAction for change_service_level, change_state and close_case when
Could we move this up so the comment is on the Constant please

2021-11-24 07:54 UTC, peterdavidhamilton commented on app/services/support/record_action.rb
> +    def call
It would be good to have the `@return` value in our docs

2021-11-24 07:56 UTC, peterdavidhamilton commented on spec/services/support/record_action_spec.rb
> +      expect(action.action).to eq "open_case"
It would be good to follow the convention of naming the POROs in the service directory as `service` in the specs. Here it would avoid having `action.action`.

2021-11-24 08:01 UTC, peterdavidhamilton commented on app/controllers/support/interactions_controller.rb
> +    def record_support_case_activity_log_item
From a design perspective would it make sense to have a common method name in our controllers for logging transactions. The controller is setting the context in my opinion, and the namespace is clarifying the database table. So `log_activity` or `record_action` could be used instead; 6 snake-cased words seems a bit unwieldy.

2021-11-24 08:08 UTC, peterdavidhamilton commented on app/controllers/support/interactions_controller.rb
> +    def record_support_case_activity_log_item
`record_case_categorisation_change`, `record_case_resolved`, `record_support_case_activity_log_item`, `record_case_opening` - These methods serve the same purpose. it would make any refactoring easier and could facilitate the Rollbar reporting. Setting it in a base controller method that we overwrite, like `super("action_name", {arbitary: "data"})`

2021-11-24 08:21 UTC, peterdavidhamilton commented
![](https://github.trello.services/images/mini-trello-icon.png) [Manual export of service activity data](https://trello.com/c/ZuoGbMQg/107-manual-export-of-service-activity-data)

2021-11-24 12:36 UTC, peterdavidhamilton commented on spec/services/support/record_action_spec.rb
> +      expect(service.call.action).to eq "open_case"
Could we assert that the log entries increment by one

2021-11-24 12:39 UTC, peterdavidhamilton commented on app/controllers/support/application_controller.rb
> +    def record_action(support_case_id:, action:, data: {})
Could we make the param `case_id`, we only have "support" floating around because of our namespacing but I don't want it to influence methods etc

2021-11-24 15:41 UTC, peterdavidhamilton approved these changes

2021-11-25 16:19 UTC, d-a-v-e approved these changes

2021-11-25 16:35 UTC, merged