Unsupported scope
DFE-Digital/buy-for-your-school pull request #680
Opened 2021-11-25 11:58 UTC by PiperS52

## Changes in this PR

- scope filters for both supported and unsupported orgs
- unsupported predicate method

2021-11-25 11:59 UTC, PiperS52 commented
![](https://github.trello.services/images/mini-trello-icon.png) [`unsupported` scope](https://trello.com/c/e31Xypqw/17-unsupported-scope)

2021-11-25 11:59 UTC, PiperS52 commented
![](https://github.trello.services/images/mini-trello-icon.png) [`unsupported?` predicate method](https://trello.com/c/BQwbA8uJ/16-unsupported-predicate-method)

2021-11-25 15:38 UTC, peterdavidhamilton commented on app/models/user.rb
> +    User.unsupported.include?(self)
Can we do without the class explicitly referencing itself

2021-11-26 13:50 UTC, d-a-v-e approved these changes

2021-11-26 13:58 UTC, EdwinKruglov commented on app/models/user.rb
> +    User.unsupported.include?(self)
We tried that, but we couldn't find a way around it. The scopes live at the class level, so it doesn't look like we can simply call them from witihn an instance method.

2021-11-29 11:33 UTC, peterdavidhamilton requested changes

2021-11-29 11:33 UTC, peterdavidhamilton commented on app/models/user.rb
> +    User.unsupported.include?(self) && User.proc_ops.exclude?(self)
```ruby
# @return [Boolean] user is not an internal team member or in a supported organisation
self.class.supported.exclude?(self) && self.class.internal.exclude?(self)
```

2021-11-29 11:33 UTC, peterdavidhamilton commented on app/models/user.rb
> +  scope :proc_ops, -> { where("orgs @> ?", %([{"name": "#{ENV['PROC_OPS_TEAM']}"}])) }
I think it's wise to rename this, only because in this context, it's not so much that they are bound for the `/support` side of things, more that they are `internal` to the project.

2021-11-29 11:33 UTC, peterdavidhamilton commented on app/models/user.rb
> +  scope :proc_ops, -> { where("orgs @> ?", %([{"name": "#{ENV['PROC_OPS_TEAM']}"}])) }
Other scope name suggestions are welcomed

2021-11-29 13:45 UTC, EdwinKruglov commented on spec/models/self-serve/user/user_supported_spec.rb
> +                 "id": "1",
If the `id` is an int then no, it doesn't work. It looks like DSI always returns the organisation type ID as a string, though.

2021-11-29 14:02 UTC, EdwinKruglov commented on spec/models/self-serve/user/user_unsupported_spec.rb
> +        expect(described_class.unsupported.count).to eq(1)
We've updated the specs so they should be easier to follow now.

2021-11-29 16:29 UTC, peterdavidhamilton approved these changes

2021-11-30 08:24 UTC, merged