Feature/98 display email body in new tab
DFE-Digital/buy-for-your-school pull request #687
Opened 2021-11-29 14:55 UTC by kennyevil

## Changes in this PR

Email support interactions will now open in a new tab.

## Screenshots of UI changes

### Before

![Screenshot 2021-11-29 at 14-53-51 Buy for your school](https://user-images.githubusercontent.com/367349/143890229-7cb5591c-5e90-4936-95a2-243e4a626096.png)

### After

![Screenshot 2021-11-29 at 14-54-26 Buy for your school](https://user-images.githubusercontent.com/367349/143890267-a3bb5995-2c88-4b02-93d9-5a97b1aae689.png)

![Screenshot 2021-11-29 at 14-54-40 Buy for your school](https://user-images.githubusercontent.com/367349/143890293-fc199278-6122-45c4-a218-e9b71725baa9.png)

2021-11-29 14:56 UTC, kennyevil commented
![](https://github.trello.services/images/mini-trello-icon.png) [Format email message in event history](https://trello.com/c/cj5olgI9/98-format-email-message-in-event-history)

2021-11-29 15:08 UTC, peterdavidhamilton commented on app/views/support/cases/case_history/_interaction.html.erb
> +          <%= interaction.show_body.html_safe %>
The presenter could have an `email?` predicate on which we could switch, that would be nice when the HTML is extracted here

2021-11-29 15:09 UTC, kennyevil commented on app/views/support/interactions/show.html.erb
> +<div class="govuk-body"><%= send(:markdown_to_html, @interaction.body) %></div>
No I don't. Brainlapse on that one. I'll change it.

2021-11-29 15:11 UTC, peterdavidhamilton requested changes

2021-11-29 15:11 UTC, peterdavidhamilton commented on spec/presenters/support/interaction_presenter_spec.rb
> +
I'd favour a feature spec that checked for the link being rendered and opening in a new tab. We have a custom matcher `have_link_to_open_in_new_tab`

2021-11-29 17:09 UTC, kennyevil commented on app/views/support/cases/case_history/_interaction.html.erb
> +          <%= interaction.show_body.html_safe %>
I've added .email? as a private method on the presenter.

2021-11-29 17:17 UTC, peterdavidhamilton approved these changes

2021-11-30 09:13 UTC, ryantk approved these changes

2021-11-30 09:32 UTC, merged