contract models
DFE-Digital/buy-for-your-school pull request #693
Opened 2021-12-02 14:57 UTC by d-a-v-e

## Changes in this PR

* Adds `NewContract`
* Adds `ExistingContract`

2021-12-02 16:01 UTC, d-a-v-e commented
![](https://github.trello.services/images/mini-trello-icon.png) [Contract data model](https://trello.com/c/rB3N1LzC/159-contract-data-model)

2021-12-03 09:06 UTC, kennyevil approved these changes

2021-12-03 09:24 UTC, AndrewCowle requested changes

2021-12-03 09:24 UTC, AndrewCowle commented on app/models/support/contract.rb
> +module Support
Can you add some documentation (like the other supported models please) just to explain what it is etc

2021-12-03 09:24 UTC, AndrewCowle commented on app/models/support/existing_contract.rb
> +
Just some docs

2021-12-03 09:24 UTC, AndrewCowle commented on spec/factories/contracts.rb
> +    supplier { "MyString" }
"Example Supplier"

2021-12-03 09:48 UTC, EdwinKruglov approved these changes

2021-12-03 11:22 UTC, merged