Feature/219 faf do you have dfe sign in
DFE-Digital/buy-for-your-school pull request #762
Opened 2022-01-12 18:10 UTC by d-a-v-e

## Changes in this PR

new dsi_or_search route, action and view

## Screenshots of UI changes
<img width="997" alt="Screenshot 2022-01-12 at 18 09 50" src="https://user-images.githubusercontent.com/6339025/149197512-b9194dde-e6ab-42bf-95a5-307942dc88b6.png">

2022-01-12 18:11 UTC, d-a-v-e commented
(FYI: this is branched off of #760 so currently has some of @PiperS52 's work)

2022-01-14 09:48 UTC, peterdavidhamilton requested changes
Can we adopt inheritance here and copy the base classes we have for schema and form that we set up in the `support` namespace first.

2022-01-14 15:24 UTC, d-a-v-e commented on app/views/fafs/steps/_step_2.html.erb
> +<br>
(this is a placeholder)

2022-01-14 15:45 UTC, EdwinKruglov commented
@d-a-v-e I can see the `Create a new DfE Sign-in account` link in the screenshot, but I don't see it in the code (except for the string in the locale file)?

2022-01-14 16:31 UTC, peterdavidhamilton approved these changes

2022-01-14 16:42 UTC, merged