In test - FaF support request start page
DFE-Digital/buy-for-your-school pull request #785
Opened 2022-01-19 14:12 UTC by PiperS52

## Changes in this PR

- This is to augment the tests in start_page_spec

2022-01-19 14:24 UTC, peterdavidhamilton commented on spec/features/self-serve/faf/start_page_spec.rb
> +      expect(page).to have_link "planning for what you're buying", href: "https://buy-for-your-school-staging.herokuapp.com/beta/phase-6/gov/buying-for-schools", class: "govuk-link"
@shafiqahmedkhan @PiperS52 we don't want links to the prototype in our code, any that have slipped through are an oversight and there is a really like hiding somewhere. Anthony can clarify that for you.

2022-01-19 14:27 UTC, peterdavidhamilton commented on spec/features/self-serve/faf/start_page_spec.rb
> +      expect(page).to have_link "create a specification", href: "https://get-help-buying-for-schools.education.gov.uk/", class: "govuk-link"
@shafiqahmedkhan @PiperS52 this is our specify internal page, but in prod we are now on `service.gov.uk`. The link should be `/dashboard` but confirm with Anthony.

2022-01-21 08:39 UTC, peterdavidhamilton requested changes
How are we doing with the link changes?

2022-01-24 16:26 UTC, peterdavidhamilton requested changes
Make use of the custom matcher `have_link_to_open_in_new_tab`

2022-01-24 17:34 UTC, shafiqahmedkhan commented
LGTM

2022-01-25 13:42 UTC, merged