260 Category and school name not being displayed
DFE-Digital/buy-for-your-school pull request #797
Opened 2022-01-21 14:53 UTC by AndrewCowle

## Changes in this PR

- added additional data to interaction presenter that formats the hash returned, removed support_request_id, added school name and category title

## Screenshots of UI changes

![Screenshot 2022-01-21 at 14 52 10](https://user-images.githubusercontent.com/7682746/150547843-b7c0e2a1-949a-4876-8a33-050349d29a3b.png)

2022-01-21 15:14 UTC, ryantk requested changes

2022-01-21 15:14 UTC, ryantk commented on app/presenters/support/interaction_presenter.rb
> +#category_id
Remove me please (#category_id)

2022-01-21 15:14 UTC, ryantk commented on app/presenters/support/interaction_presenter.rb
> +    def organisation(organisation_id)
Might be good to use the Presenters for these, just in case the format changes

2022-01-21 15:14 UTC, ryantk commented on spec/presenters/support/interaction_presenter_spec.rb
> +        expect(presenter.additional_data).to include("category_id" => "Example Category")
Does the field display as "Category Id" on the page?
Now we are not subbing the _id from the key do we need to update any locale files?

2022-01-23 20:49 UTC, AndrewCowle commented on spec/presenters/support/interaction_presenter_spec.rb
> +        expect(presenter.additional_data).to include("category_id" => "Example Category")
Nope - the screenshot shows "Buying Category" :)

2022-01-23 21:24 UTC, AndrewCowle commented on app/presenters/support/interaction_presenter.rb
> +    def organisation(organisation_id)
Good spot :)

2022-01-24 09:25 UTC, ryantk approved these changes

2022-01-24 12:10 UTC, kennyevil approved these changes

2022-01-25 10:05 UTC, merged