FaF support request - updates to DfE signed in journey for MATs
DFE-Digital/buy-for-your-school pull request #855
Opened 2022-02-08 13:45 UTC by PiperS52

## Changes in this PR

- updated content for kick-out page 
- (work in progress)

## Screenshots of UI changes

### Before

### After

2022-02-11 16:58 UTC, kennyevil approved these changes

2022-02-11 17:49 UTC, peterdavidhamilton requested changes

2022-02-11 17:49 UTC, peterdavidhamilton commented on app/forms/framework_support_form_schema.rb
> +  rule do
Can you change it so there is an `affiliation` rule with a `missing` key please.

2022-02-11 17:49 UTC, peterdavidhamilton commented on app/forms/framework_support_form_schema.rb
> +      Support::EstablishmentGroup.find_by(uid: id).present?
Same thing here about accessing supported data. What I'd like is a function that if provided an identifier will return a hash of everything we need for use in Specify if it looked the same as the DSI orgs array we would have a common interface. Add a note same as in the controller.

2022-02-11 17:49 UTC, peterdavidhamilton commented on app/views/framework_requests/show.html.erb
> +            <%= link_to I18n.t("generic.button.change_answer"), edit_framework_request_path(@framework_request, step: 3), class: "govuk-link", id: "edit-school" unless current_user.supported_orgs.one
`single_org?`

2022-02-11 17:49 UTC, peterdavidhamilton commented on app/views/framework_requests/steps/_step_3.html.erb
>  <% elsif form.object.group == true %>
We could drop the `== true` but this is an opportunity to build the interface of the form, so we could have:

```ruby
def multiple_schools?
  instance_variable_get :@group
end
```

Be aware the `group` attribute has been duplicated in the form

2022-02-14 10:57 UTC, peterdavidhamilton approved these changes

2022-02-14 11:00 UTC, merged