#234 FaF Support Request - Modify eligibility check so MATs are eligible
DFE-Digital/buy-for-your-school pull request #863
Opened 2022-02-10 14:58 UTC by EdwinKruglov

## Changes in this PR

- allow users belonging to groups (MATs and SATs) to use the service

2022-02-10 14:58 UTC, EdwinKruglov commented
![](https://github.trello.services/images/mini-trello-icon.png) [#234 FaF Support Request - Modify eligibility check so MATs are eligible](https://trello.com/c/FsL0CRnT/220-234-faf-support-request-modify-eligibility-check-so-mats-are-eligible)

2022-02-10 16:14 UTC, peterdavidhamilton requested changes

2022-02-10 16:14 UTC, peterdavidhamilton commented on app/services/create_user.rb
> +  def establishment_categories
I think you should refactor the existing `org` query method to cater for querying `type` or `category` depending on a param. Then have the `supported?` predicate call two new methods that use it i.e. `supported_establishment? || supported_establishment_group?` (however these names are CM aware so in this context perhaps `valid_school? || valid_trust?`)

2022-02-10 17:09 UTC, peterdavidhamilton approved these changes

2022-02-11 12:12 UTC, PiperS52 approved these changes

2022-02-11 12:25 UTC, merged