Updated help with formatting text
DFE-Digital/buy-for-your-school pull request #883
Opened 2022-02-16 16:06 UTC by kennyevil

## Changes in this PR

Updated the content of  the "help with formatting" section for non-templated emails.

## Screenshots of UI changes
![Screenshot 2022-02-16 at 16-05-46 Buy for your school](https://user-images.githubusercontent.com/367349/154306409-973698e3-b6b7-4785-88d2-af66e19232ec.png)

2022-02-16 16:06 UTC, kennyevil commented
![](https://github.trello.services/images/mini-trello-icon.png) [Update the 'Help with formatting' information on the Non templated email](https://trello.com/c/blYj16xW/335-update-the-help-with-formatting-information-on-the-non-templated-email)

2022-02-16 18:24 UTC, peterdavidhamilton commented on app/views/support/cases/emails/content/_help_with_formatting.en.html.erb
> +      Email addresses will automatically fromat as a link:
`format`

2022-02-17 11:49 UTC, quaypho commented on app/views/support/cases/emails/content/_help_with_formatting.en.html.erb
> +      Use a number followed by a full stop to make numbered lists. The line above <b> * point 1 </b> should be blank:
The last sentence should be 'The line above <b> 1. Add numbers </b> should be blank:

2022-02-17 11:55 UTC, quaypho commented on app/views/support/cases/emails/content/_help_with_formatting.en.html.erb
> +    <h2 class="heading-medium">Links and URLs</h2>
I think this should be a h3 for consistency

2022-02-17 11:56 UTC, quaypho commented on app/views/support/cases/emails/content/_help_with_formatting.en.html.erb
> +    <h2 class="heading-medium">Email addresses</h2>
I think this should be a h3 for consistency

2022-02-17 11:58 UTC, quaypho commented on app/views/support/cases/emails/content/_help_with_formatting.en.html.erb
> +
There is a missing section. The 'New line' section should be here.

2022-02-17 11:59 UTC, quaypho requested changes
Just a few bits and bobs need editing/updating

2022-02-17 12:57 UTC, kennyevil commented on app/views/support/cases/emails/content/_help_with_formatting.en.html.erb
> +
I've added that in now.

2022-02-17 13:42 UTC, peterdavidhamilton approved these changes
FYI the schema is getting commit too

2022-02-17 13:57 UTC, quaypho requested changes

2022-02-17 13:57 UTC, quaypho commented on app/views/support/cases/emails/content/_help_with_formatting.en.html.erb
> +      Use a number followed by a full stop to make numbered lists. The line above <b> * 1. Add numbers </b> should be blank:
Please remove the *

2022-02-17 13:57 UTC, quaypho commented on app/views/support/cases/emails/content/_help_with_formatting.en.html.erb
> +      adding two spaces at the end of a line will create a 'soft' new line (equivalent to pressing the return key in a text editor)
Please can we change this to:

To add a new line, use 2 spaces and press **enter/return**

This is the first line (add 2 spaces and press **enter/return)**
This is the second line

2022-02-17 14:05 UTC, shafiqahmedkhan approved these changes

2022-02-17 14:37 UTC, merged