Case worker can reopen a resolved case
DFE-Digital/buy-for-your-school pull request #887
Opened 2022-02-17 16:32 UTC by PiperS52

## Changes in this PR

- added aasm gem state machine with event transitions, refactoring assignments_controller and resolutions_controller, as well as added relevant openings_controller and closings_controlller
- 'reopen case' and 'close case'  functionality in case management
- incoming email received on a 'resolved' case reopens it
- incoming email received on a 'closed' case creates a new case
- 'pending' state renamed to 'on_hold'
- ```Support::Case``` state changes recorded to ```ActivityLogItem```

2022-02-21 17:44 UTC, PiperS52 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Case worker can re-open a resolved case](https://trello.com/c/PYeElWIo/199-case-worker-can-re-open-a-resolved-case)

2022-02-21 17:45 UTC, PiperS52 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Proc ops to be able to change the status of a case](https://trello.com/c/js9UjNET/366-proc-ops-to-be-able-to-change-the-status-of-a-case)

2022-02-22 09:01 UTC, peterdavidhamilton reviewed
Please can you add an achitecture decision record to justify the inclusion of the AASM library.

2022-02-22 10:30 UTC, peterdavidhamilton approved these changes

2022-02-24 15:24 UTC, ryantk requested changes

2022-02-24 15:24 UTC, ryantk commented on app/controllers/support/cases/closures_controller.rb
> +        current_case.interactions.note.build(
Instead of note could you add a new interaction type of "status change" or something to that effect? I think we will like to know the specific reason for the interaction in the future.

2022-02-24 15:24 UTC, ryantk commented on app/controllers/support/cases/on_holds_controller.rb
> +        current_case.interactions.note.build(
Same as above

2022-02-25 09:21 UTC, ryantk approved these changes

2022-02-25 11:50 UTC, d-a-v-e approved these changes

2022-03-01 13:50 UTC, merged