Able to change Contact and Org on 'closed' case - should be disabled
DFE-Digital/buy-for-your-school pull request #895
Opened 2022-02-22 16:17 UTC by PiperS52

## Changes in this PR

- branched from https://github.com/DFE-Digital/buy-for-your-school/pull/887
- remove change links from school details tab in CM when case closed

## Screen-shots or screen-capture of UI changes

### After

<img width="1096" alt="Screenshot 2022-02-22 at 16 12 04" src="https://user-images.githubusercontent.com/62155037/155173234-152295d6-02f7-49a8-9717-621f584b4a57.png">

2022-02-23 15:18 UTC, ryantk requested changes

2022-02-23 15:18 UTC, ryantk commented on app/services/support/incoming_emails/case_assignment.rb
> +        new_case_for_email unless email.sent_items?
In the scenario "Create a new case when existing one is closed" this might not work end to end.

If you look at this line: https://github.com/DFE-Digital/buy-for-your-school/blob/16f38c00286be105e757319b94cbc78b5f0e2ab7/app/models/support/email.rb#L51 

The assignment of the case will be bypassed because it already has a case_id (although closed).

2022-02-23 16:43 UTC, PiperS52 commented on app/services/support/incoming_emails/case_assignment.rb
> +        new_case_for_email unless email.sent_items?
Good spot. @ryantk is it possible to turn line 51 into `return if case_id.present? && !self.case.closed?`

2022-02-25 11:16 UTC, PiperS52 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Able to change contact and Org on a 'Closed' case. Should be disabled.](https://trello.com/c/HSL2NKac/380-able-to-change-contact-and-org-on-a-closed-case-should-be-disabled)

2022-02-28 15:20 UTC, EdwinKruglov approved these changes

2022-02-28 16:41 UTC, d-a-v-e approved these changes

2022-03-01 14:28 UTC, ryantk approved these changes

2022-03-01 14:28 UTC, merged